### ISSUE TITLE
Error while "Extracting Strings from APK"

### ISSUE THREAD

**Issue by orenyomtov** [ajinabraham/YSO-Mobile-Security-Framework#48]
```
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more
```

APK:
https://play.google.com/store/apps/details?id=com.Slack

**Comment by ajinabraham** [comment]
Known issue. Strings cannot be extracted from some APKs.
Will investigate on this.

**Comment by bugwrangler** [comment]
yep, it has been observed couple times. 

Two Cents from my side :+1: 
As per gartner's survey Veracode doesn't even allow to scan binary without supporting libs & debug flag - compare to veracode - Mobile security Framework is doing the better job.  at other hand IBM & HP can't event stand against static analysis result.

**Comment by ajinabraham** [comment]
The issue is with a third-party tool named "strings_from_apk.jar". We have to wait till the developer of the tool fixes that or else I need to re-write that tool.
